#!/bin/sh
bigintat () {
	hexdump -e'/8 "%d"' -n8 -s$2 $1
}
bytesat () {
	hexdump -e'/1 "%02X"' -n$3 -s$2 $1 -v
}
eflags () {
	intat $1 48
}
epof () {
	bigintat $1 24
}
intat () {
	hexdump -e'/4 "%d"' -n4 -s$2 $1
}
isanelf () {
	if [ -x $1 ]
	then
		first4=$(hexdump -v -e'"%X"' -n4 $1)
		if [ $first4 = 464C457F ]
		then
			return 0
		else
			return 1
		fi
	else
		return 1
	fi
}
phentsize () {
	wordat $1 54
}
phnum () {
	wordat $1 56
}
phof () {
	bigintat $1 32
}
runflags () {
	idx=0
	encoded=$1
	shift
	for flagname in $@
	do
		proof=$(($encoded>>$idx))
		if test $(($proof&1)) -gt 0
		then
			echo $flagname
		fi
		idx=$(($idx+1))
	done
}
		
shentsize () {
	wordat $1 58
}
shnum () {
	wordat $1 60
}
shof () {
	bigintat $1 40
}
wordat () {
	hexdump -e'/2 "%d"' -n2 -s$2 $1
}
